language: "haskell"
ghc: 7.8

before_install:
  - cabal install alex
  - cabal install --only-dependencies --enable-tests

install:
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build

script:
  - cabal test

after_script:
 - cabal install hpc-coveralls
 - hpc-coveralls tests

notifications:
  email:
    recipients: omeragacan@gmail.com
    on_success: change
    on_failure: change
